services:
    api-server:
        volumes:
            - ./data:/usr/local/data
            - ./env:/usr/local/env
    depends_on:
        - my_new_postgres
    networks:
        - ariflow
    scheduler:
        volumes:
            - ./data:/usr/local/data
            - ./env:/usr/local/env
    depends_on:
        - my_new_postgres
    networks:
        - ariflow
    triggerer:
        volumes:
            - ./data:/usr/local/data
            - ./env:/usr/local/env
    depends_on:
        - my_new_postgres
    networks:
        - ariflow
    dag-processor:
        volumes:
            - ./data:/usr/local/data
            - ./env:/usr/local/env
    depends_on:
        - my_new_postgres
    networks:
        - ariflow
    
    my_new_postgres:
        image: postgres:15
        container_name: my_new_postgres
        environment:
            POSTGRES_USER: phongthanh
            POSTGRES_PASSWORD: thangkhung0993
            POSTGRES_DB: stock_database
        ports:
            - "5433:5432"
        networks:
            - ariflow
networks:
    ariflow:
        driver: bridge